import { useState } from "react";
import { Mail, Loader2, Check } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";
import type { WarRoomReport } from "./ValidationReport";

interface EmailReportButtonProps {
  report: WarRoomReport;
  idea: string;
}

const EmailReportButton = ({ report, idea }: EmailReportButtonProps) => {
  const [email, setEmail] = useState("");
  const [isOpen, setIsOpen] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [sent, setSent] = useState(false);

  const handleSend = async () => {
    if (!email.trim() || !email.includes("@")) {
      toast({ title: "Invalid email", description: "Please enter a valid email.", variant: "destructive" });
      return;
    }

    setIsSending(true);
    try {
      const { data, error } = await supabase.functions.invoke("email-report", {
        body: { email, report, idea },
      });

      if (error) throw error;
      if (data?.error) {
        toast({ title: "Failed", description: data.error, variant: "destructive" });
        return;
      }

      // Open mailto with the formatted content
      const subject = encodeURIComponent(data.subject || `VentureVitals Report — Score ${report.score}/100`);
      const body = encodeURIComponent(
        `VentureVitals Validation Report\n\n` +
        `Idea: ${idea}\n` +
        `Score: ${report.score}/100\n` +
        `Confidence: ${report.confidenceLevel}\n` +
        `Verdict: ${report.verdict}\n\n` +
        `Executive Summary:\n${report.step4_finalReport?.executiveSummary || ''}\n\n` +
        `Major Risks:\n${report.step4_finalReport?.majorRisks?.map(r => `• ${r}`).join('\n') || 'None'}\n\n` +
        `Opportunities:\n${report.step4_finalReport?.opportunitySignals?.map(o => `• ${o}`).join('\n') || 'None'}\n\n` +
        `— Generated by VentureVitals (venturevitals.lovable.app)`
      );

      window.open(`mailto:${email}?subject=${subject}&body=${body}`, '_blank');

      setSent(true);
      toast({ title: "Email ready!", description: "Your email client should open with the report." });
      setTimeout(() => { setSent(false); setIsOpen(false); }, 3000);
    } catch {
      toast({ title: "Error", description: "Failed to prepare email.", variant: "destructive" });
    } finally {
      setIsSending(false);
    }
  };

  if (!isOpen) {
    return (
      <button
        onClick={() => setIsOpen(true)}
        className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-border bg-card text-sm font-medium text-foreground hover:bg-secondary transition-colors"
      >
        <Mail className="w-4 h-4" /> Email Report
      </button>
    );
  }

  return (
    <div className="inline-flex items-center gap-2 p-1 rounded-lg border border-border bg-card">
      <input
        type="email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        placeholder="your@email.com"
        className="px-3 py-1.5 bg-transparent text-sm text-foreground placeholder:text-muted-foreground/50 focus:outline-none w-48"
        onKeyDown={(e) => e.key === "Enter" && handleSend()}
      />
      <button
        onClick={handleSend}
        disabled={isSending || sent}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-primary text-primary-foreground text-xs font-medium hover:bg-primary/90 transition-colors disabled:opacity-40"
      >
        {sent ? (
          <><Check className="w-3 h-3" /> Sent</>
        ) : isSending ? (
          <><Loader2 className="w-3 h-3 animate-spin" /> Sending…</>
        ) : (
          <><Mail className="w-3 h-3" /> Send</>
        )}
      </button>
    </div>
  );
};

export default EmailReportButton;
